baseURL = 'georgelarkwright.com'
languageCode = 'en-uk'
Title = 'George Larkwright'

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]


[Navigation]
    [[Navigation.item]]
    name = "Home"
    title = "About"
    url = "/"
    [[Navigation.item]]
    name = "Projects"
    title = "Projects"
    url = "/projects"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true
